### ISSUE TITLE
deprecated conversion from string constant to 'char*' in esp8266-weather-station-color.ino

### ISSUE THREAD

**Issue by awumaker** [ThingPulse/esp8266-weather-station-color#13] opened 2017-05-02 18:11 UTC
My compiler shows me the same warnings for the following lines: 92, 148, 149, 153, 299, 306

Example (line 92):
  ui.drawString(120, 160,  "Connecting to WiFi");

WARNING:
.../src/main.ino: In function 'void setup()':
.../src/main.ino:94:47: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings] ui.drawString(120, 160, "Connecting to WiFi");

When I change it to:
  ui.drawString(120, 160, (char*) "Connecting to WiFi");

No WARNINGS at all.

It seems, that drawString() needs a pointer and not a string.
It is still working with the string, but the cleaner solution with the pointer.

Maybe it helps for a cleaner code.

**Comment by marcelstoer** [comment] 2018-04-14 21:44
Cannot reproduce -> closing

**Closed by marcelstoer** 2018-04-14 21:44 UTC
